services:
  postgres:
    image: 'postgres:17.2-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379'
